Stokvel Groups Home/Models/AccountUser.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stokvel_Groups_Home.Models;

public class AccountUser
{

	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public string? Id { get; set; }


	[Required(ErrorMessage = "Please Fill In Your Name")]
	[StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
	[Column("FirstName")]
	[Display(Name = "First Name")]
	public string? FirstName { get; set; }



	[Required(ErrorMessage = "Please Fill In Your Lastname")]
	[Display(Name = "Last Name")]
	[StringLength(50)]
	public string? LastName { get; set; }

	[NotMapped]
	[DisplayName("Profile Picture")]
	[DataType(DataType.Upload)]
	[FileExtensions(Extensions = "jpg,png,gif,jpeg,bmp,svg")]
	public IFormFile? ProfilePicture { get; set; }
	public string? MemberPhotoPath { get; set; }
	public string? MemberFileName { get; set; }


	[Required(ErrorMessage = "Please Fill In Your address")]
	public string? Address { get; set; }
	[Required(ErrorMessage = "Please Fill In Your City")]
	public string? City { get; set; }


	[Required(ErrorMessage = "Please Fill In Your Province")]
	public string? Province { get; set; }
	[Required(ErrorMessage = "Please Fill In Your Zip")]
	public int Zip { get; set; }

	
	[DataType(DataType.Date)]
	[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
	public DateTime Date { get; set; }


	public virtual IEnumerable<Account>? UserAccounts { get; set; }
	public virtual IEnumerable<AccountProfile>? AccountProfiles { get; set; }


}

Stokvel Groups Home/Controllers/AccountUsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stokvel_Groups_Home.Interface.Infrastructure;
using Stokvel_Groups_Home.Interface.IServices.IAccountUserServices;
using Stokvel_Groups_Home.Models;
using X.PagedList;


namespace Stokvel_Groups_Home.Controllers
{
	public class AccountUsersController : Controller
	{

		private readonly IInputFoldersRepository _unitOfWork;
		private readonly IAccountUserCRUDService _accountUserCRUDService;
		private readonly IAccountUserRequestServices _accountUserRequestServices;

		public AccountUsersController(IInputFoldersRepository unitOfWork, IAccountUserCRUDService accountUserCRUDService, IAccountUserRequestServices accountUserRequestServices)
		{

			_unitOfWork = unitOfWork;
			_accountUserCRUDService = accountUserCRUDService;
			_accountUserRequestServices = accountUserRequestServices;
		}

		// GET: AccountUsers
		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<ViewResult> AdminIndex(string sortOrder, string currentFilter, string searchString, int? page)
		{
			if (!User.IsInRole("Admin"))
			{
				return View(RedirectToAction("Index", "Home"));

			}

            ViewBag.image = "/wwwroot/images/Profile";
            ViewBag.CurrentSort = sortOrder;
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
			ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";


			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			var accountUsers = await _accountUserRequestServices.FilterAccountUsers(sortOrder, currentFilter, searchString, page);

			return View(accountUsers.ToPagedList());
		}



		// GET: AccountUsers
		public async Task<ViewResult> Index()
		{
			var id = User.Identity.GetUserId();
			var accountUsers = await _accountUserCRUDService.GetAll();

			var member = accountUsers.Where(x => x.Id == id).ToList();
			ViewBag.image = "/wwwroot/images/Profile";

			return View(member);
		}

		// GET: AccountUsers/Details/5
		[HttpGet]
		public async Task<IActionResult> Details(string? id)
		{
			var accountUser = await _accountUserCRUDService.GetById(id);
			if (id == null || accountUser == null)
			{
				return NotFound();
			}

			return View(accountUser);
		}

		// GET: AccountUsers/Create
		public async Task<IActionResult> Create()
		{
			var UserId = User.Identity.GetUserId();
			var newUserVerify = await _accountUserCRUDService.GetById(UserId);

			if (newUserVerify != null)
			{
				return RedirectToAction(nameof(AdminIndex));
			}
			return View();
		}

		// POST: AccountUsers/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,MemberPhotoPath,MemberFileName,Address,City,Province,Zip,Date")] AccountUser? accountUser)
		{


			if (ModelState.IsValid)
			{
				//Gets User Id
				var UserId = User.Identity.GetUserId();

				//Checks If User Already Exists
				var newUserVerify = await _accountUserCRUDService.GetById(UserId);

				if (newUserVerify != null || accountUser is not null)
				{
					if (HttpContext.Request.Form.Count > 0 && HttpContext.Request.Form.Files.Count > 0)
					{
						var uploadedImage = HttpContext.Request.Form.Files[0];
						accountUser.Id = UserId;
						accountUser.Date = DateTime.Now;

						await _unitOfWork.UploadImage(accountUser, uploadedImage);
					}
					else
					{
						accountUser.Id = UserId;
						accountUser.Date = DateTime.Now;
						accountUser.MemberPhotoPath = "~/wwwroot/images/Profile";
						await _accountUserCRUDService.Insert(accountUser);
						await _accountUserCRUDService.SaveAsync();
					}
					return RedirectToAction(nameof(Index));
				}
			}
			else
			{
				return View();
			}
			return View(accountUser);
		}

		// GET: AccountUsers/Edit/5
		public async Task<IActionResult> Edit(string id)
		{
			
			var accountUser = await _accountUserCRUDService.GetById(id);
			if (id == null || accountUser == null)
			{
				return NotFound();
			}

            return View(accountUser);
		}

		// POST: AccountUsers/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,MemberPhotoPath,MemberFileName,Address,City,Province,Zip,Date")] AccountUser accountUser)
		{
			if (id != accountUser.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
                   
                    accountUser.Date = DateTime.Now;
                    accountUser.MemberPhotoPath = "~/wwwroot/images/Profile";
                    _accountUserCRUDService.Edit(accountUser);
					await _accountUserCRUDService.SaveAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!AccountUserExists(accountUser.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(accountUser);
		}

		// GET: AccountUsers/Delete/5
		[HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Delete(string id)
		{
			var accountUser = await _accountUserCRUDService.GetById(id);
			if (id == null || accountUser == null)
			{
				return NotFound();
			}

			return View(accountUser);
		}

		// POST: AccountUsers/Delete/5
		[HttpPost, ActionName("Delete")]
		[Authorize(Roles = "Admin")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(string id)
		{
			var accountUser = await _accountUserCRUDService.GetById(id);

			if (id == null || accountUser == null)
			{
				return Problem("Entity set 'ApplicationDbContext.AccountUsers'  is null.");
			}
			await _accountUserCRUDService.Delete(id);
			await _accountUserCRUDService.SaveAsync();


			return RedirectToAction(nameof(Index));
		}

		private bool AccountUserExists(string id)
		{
			return (_accountUserCRUDService.AccountUserExists(id));
		}
	}
}

Stokvel Groups Home/Views/AccountUsers/AdminIndex.cshtml
@model IPagedList<Stokvel_Groups_Home.Models.AccountUser>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!-- row -->
<div class="midde_cont">

    <div class="row column_title">
        <div class="col-md-12">
            <div class="page_title">
                <h2>AccountUsers</h2>
            </div>
        </div>
    </div>
    <!-- row -->


    <nav aria-label="breadcrumb" class="bg-white rounded-3 p-3 mb-4">
        <div class="row">

            <div class="col-md-6">

                @if (User.IsInRole("Member"))
                {
                    <a class="btn btn-outline-danger" asp-controller="Accounts" asp-action="Create">Create New</a>
                }
                else
                {
                    <a class="btn btn-outline-danger" asp-controller="Home" asp-action="Index">Home</a>
                }

            </div>
            <div class="col-md-6">

                @using (Html.BeginForm("AdminIndex", "AccountUsers", FormMethod.Get))
                {
                    <p>
                        Find by name: @Html.TextBox("SearchString", (object)ViewBag.CurrentFilter as string)

                        <input type="submit" value="Search" />
                    </p>
                }

            </div>

            <alerts></alerts>

        </div>
    </nav>

    <!-- row -->
    <div class="row column1">
        <div class="col-md-12">
            <div class="white_shd full margin_bottom_30">
                <div class="full graph_head">
                    <div class="heading1 margin_0">
                        <h2>Join a Group</h2>
                    </div>
                </div>
                <div class="full price_table padding_infor_info">
                    <div class="row">


                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.Hidden("Id")
                                    </th>
                                    <th>
                                        FirstName
                                    </th>
                                    <th>
                                        @Html.ActionLink("LastName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th>
                                       ProfilePicture
                                    </th>
                                    <th>
                                        Address
                                    </th>
                                    <th>
                                        City
                                    </th>
                                    <th>
                                       Province
                                    </th>
                                    <th>
                                       Zip
                                    </th>
                                    <th>
                                        @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
                                    </th>
                                    <th>
                                        Options
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                   
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FirstName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.LastName)
                                        </td>
                                        <td>
                                           @if(Url.Content(item.MemberPhotoPath) != ViewBag.image)
											{
                                                <img src="@Url.Content("~/ images / MemberProfile / " + @item.MemberFileName)" height="95px" width="95px" />
											}
                                            else
                                            {
                                                <img src="@Url.Content("~/ images / Profile / " + @item.MemberFileName)" height="95px" width="95px" />
											}
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Address)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.City)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Province)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Zip)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Date)
                                        </td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                        <br />
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount


                        @Html.PagedListPager(Model, page => Url.Action("AdminIndex",
                                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Stokvel Groups Home/Views/AccountUsers/Delete.cshtml
@model Stokvel_Groups_Home.Models.AccountUser

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AccountUser</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Stokvel Groups Home/Views/AccountUsers/Details.cshtml
@model Stokvel_Groups_Home.Models.AccountUser

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AccountUser</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Stokvel Groups Home/Views/AccountUsers/Index.cshtml
@model IEnumerable<Stokvel_Groups_Home.Models.AccountUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- row -->
<div class="midde_cont">

    <div class="row column_title">
        <div class="col-md-12">
            <div class="page_title">
                <h2>Account</h2>
            </div>
        </div>
    </div>
    <!-- row -->


    <nav aria-label="breadcrumb" class="bg-white rounded-3 p-3 mb-4">
        <div class="row">

            <div class="col-md-6">

                @if (User.IsInRole("Member"))
                {
                    <a class="btn btn-outline-danger" asp-controller="Accounts" asp-action="Create">Create New</a>
                }
                else
                {
                    <a class="btn btn-outline-danger" asp-action="Create">Create New</a>

                }

            </div>
            <div class="col-md-6">

                @using (Html.BeginForm("Index", "Groups", FormMethod.Get))
                {
                    <p class="text-end">
                        Find by name: @Html.TextBox("SearchString", (object)ViewBag.CurrentFilter as string)
                        <input type="submit" value="Search" class="btn btn-outline-secondary " />
                    </p>
                }

            </div>

            <alerts></alerts>

        </div>
    </nav>

    <!-- row -->
    <div class="row column1">
        <div class="col-md-12">
            <div class="white_shd full margin_bottom_30">
                <div class="full graph_head">
                    <div class="heading1 margin_0">
                        <h2>Account</h2>
                    </div>
                </div>
                <div class="full price_table padding_infor_info">
                    <div class="row">


                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.Hidden("Id")
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.FirstName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.LastName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ProfilePicture)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Address)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.City)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Province)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Zip)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Date)
                                    </th>
                                    <th>Options</th>
                                </tr>
                            </thead>
                            <tbody>
                        @foreach (var item in Model) {
                                <tr>
                                        <td>
                                        </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LastName)
                                    </td>
                                    <td>
                                            @if (Url.Content(item.MemberPhotoPath) != ViewBag.image)
                                            {
                                                <img src="@Url.Content("~/images/MemberProfile/" + @item.MemberFileName)" height="120px" width="120px"/>
                                            }
                                            else
                                            {
                                                <img src="@Url.Content("~/images/Profile/" + @item.MemberFileName)" height="120px" width="120px" />
                                            }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Address)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.City)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Province)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Zip)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Date)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                        }
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>